### ISSUE TITLE
Boilerplate generation does not work

### ISSUE THREAD

**Issue by alaporterie** [julmot/jmBoilerplate#1]
Hi,

when I performed 'yo jmboilerplate', I get this issue with default config parameters:

ReferenceError: /Users/xxxxx/.cache/yeoman/julmot/jmBoilerplate/master/Gruntfile.js:48
    46|         project: {
    47|             app: '.',

> > 48|             build: '<%= project.app %>/build',
> >     49|             dist: {
> >     50|                 web: '<%= project.app %>/dist/web-v<%= pkg.version %>',
> >     51|                 // for later coming hybrid app compatibility:

project is not defined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:11:23)
    at returnedFn (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/ejs/lib/ejs.js:514:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/ejs/lib/ejs.js:316:37)
    at copy.process (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl](/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:8)
    at template (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at copy (/usr/local/lib/node_modules/generator-jmboilerplate/node_modules/yeoman-generator/lib/actions/actions.js:43:10)

Could you help me please?
I have successfully installed yeoman and generator-jmboilerplate without any errrors.

You boilerplate seems to be very useful for me.

Thanks,
Anthony

**Comment by julkue** [comment]
I am sorry to hear that. I will dig into this soon.

**Comment by julkue** [comment]
The problem is in this line:

``` javascript
remote.copy('Gruntfile.js', 'Gruntfile.js');
```

`copy` in this case will trigger ejs template rendering, which will of course not work.  
As I don't see an option to disable ejs rendering when copying from a remote and there is another issue targeting the copy process (https://github.com/yeoman/generator/issues/903) the only option seems to be storing jmBoilerplate as part of generator-jmboilerplate.

This will take some time, so in the meantime please set up the project yourself as described in the [wiki](https://github.com/julmot/jmBoilerplate/wiki/Manual-setup).

**Comment by julkue** [comment]
@alaporterie I've refactored the generator. Things should work now. 
Please give me a short feedback if everything is ok now on your end. 
Sorry for the inconvenience!

**Comment by alaporterie** [comment]
Ok thank you!
